// <auto-generated />
namespace Projeto_Copa_do_Mundo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Atualizacoes5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Atualizacoes5));
        
        string IMigrationMetadata.Id
        {
            get { return "201711041846575_Atualizacoes5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
